version: '3'
services:
  postgres:
    build:
      context: ./webapp/deployment/local/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/abh-restaurants?currentSchema=restaurants
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "4200:4200"