version: '3'
services:
  postgres:
    image: "postgres:11.3"
    volumes:
      - ./postgres/:/postgres-init-data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
