#
# Application configuration
# This is production first application configuration; Override specific parts of this configuration in appropriate profile sections down below.
#
spring:
  port: 8080

  profiles:
    active: @activeProfile@

  flyway:
    locations:
      "classpath:database/migrations"

  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQL9Dialect"
    open-in-view: false
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false

  session:
    store-type: "jdbc"
    jdbc.initialize-schema: "always"

  # Disable default resource mapping; Disable templates
  resources.add-mappings: false
  thymeleaf:
    enabled: false
    checkTemplateLocation: false

logging:
  level:
    root: TRACE

---
#
# Develop profile
#
spring:
  profiles: develop

  datasource:
    url: jdbc:postgresql://localhost:5432/abh-restaurants?currentSchema=restaurants
    username: postgres
    password: postgres

---
#
# Integration profile
#
spring:
  profiles: integration

  datasource:
    embedded-pg:
      host: localhost
      port: 31116
      name: starter-app-db

# App related config

---
# Production profile
spring:
  profiles: production
